### ISSUE TITLE
Hairdresser/Administrator Login

### ISSUE THREAD

**Issue by ahuston-0** [PresidentSkroob/CS_546_Final_Project#8]
Allows salon employees/managers/etc to login to accounts with special permissions. Hairdressers can view their upcoming appointments, view analytics, etc.

## Requirements
- [x] Administrator route only accessible to authorized users i.e. admin, employees
- [x] Be able to display a view of all appointments in the past/future
- [x] Display analytics TBD; ideally visualized.

**Comment by ahuston-0** [comment]
Reopening because only 1/3 requirements were met by the merge in question.

**Comment by jkronyak** [comment]
woops
